### ISSUE TITLE
legacy api

### ISSUE THREAD

**Issue by Eldinnie** [SukiCZ/boardgamegeek#57]
Hi there, 

The original project had a legacy api for the v1 api (which is the only way to retreive geeklists.
I saw you fork here, and hoped it would fix the issue with `BGGClientLegacy` not being expost in `__init__.py` but it seems you completely removed the file.
am I missing the point where it is reimplemented? Or did you simply remove it?

**Comment by SukiCZ** [comment]
Hi @Eldinnie

It seems the legacy API was only implemented in the `develop` branch. I'll try to merge it and expose it in the init file. Thanks for letting me know

**Comment by SukiCZ** [comment]
I've merged with `develop` branch and release new version `1.1.7`. You should be able to get a geek-list with the following

```py
from boardgamegeek import BGGClientLegacy

bgg = BGGClientLegacy()

# https://boardgamegeek.com/xmlapi/geeklist/1
lst = bgg.geeklist(1)

assert lst.name == "First 10 Games Added to BGG"
assert lst.username == "Aldie"
```

**Comment by Eldinnie** [comment]
absolutely fantastic!
Thanks for the very quick response and fix!
