### ISSUE TITLE
Can't git clone on Windows because of '?' in file names

### ISSUE THREAD

**Issue by SukiCZ** [SukiCZ/boardgamegeek#58]
See upstream issue lcosmin/boardgamegeek#58 and commit lcosmin/boardgamegeek@504f56c for details.

One way to fix this is replacing `?` with `@`

**Comment by Eldinnie** [comment]
Was about to post this same issue.
I wanted to contribute to this project, but cannot clone my fork in order to work on it locally

**Comment by SukiCZ** [comment]
@Eldinnie I've got a solution for you - Use Linux! :laughing: 

It has been fixed :pray:
