### ISSUE TITLE
Thing requests now limited to 20 items at a time

### ISSUE THREAD

**Issue by Eldinnie** [SukiCZ/boardgamegeek#79]
As you can see on https://boardgamegeek.com/wiki/page/BGG_XML_API2 the thing api is now limited to 20 games at a time. This has an influence on  `client.game_list()`

**Comment by SukiCZ** [comment]
Oh, they've added this like a month ago? :laughing: I was hoping messing up with `page` or `pagesize` parameters would help but no, everytime I provide a list of 21+ game IDs I get [400 response](http://http.cat/status/400).

I guess the only thing we can do is add a validation for a `len(game_id_list)` and `raise BGGError` in such situation. You care to open a Pull Request?

**Comment by Eldinnie** [comment]
Sorry, I currently can;t really find time to contribute, but very glad you managed to solve it quickly :D
