### ISSUE TITLE
Collection request with unpopulated 'yearpublished' values

### ISSUE THREAD

**Issue by fgoicovic** [SukiCZ/boardgamegeek#80]
I am trying to use this library to get my collection from BGG, but all the items are returning `yearpublished=0`. For what I can gather, this is the default value when the parser cannot find the parameter in the XML response.

**Comment by SukiCZ** [comment]
I would recommend using `year` attribute instead but `yearpublished` should work too. Following example works fine

```py
>>> from boardgamegeek import BGGClient
>>> 
>>> bgg = BGGClient()
>>> 
>>> game = bgg.game(game_id=1406)
>>> print(game.year)
1935
>>> print(game.yearpublished)
1935
```

https://boardgamegeek.com/xmlapi2/thing?id=1406

Which game (and how) are you trying to fetch?

**Comment by SukiCZ** [comment]
Sorry, I see you were talking about [Collections](https://boardgamegeek.com/xmlapi2/collection?username=shulyah&subtype=boardgame&stats=1). I'll release a fix now

**Comment by fgoicovic** [comment]
Thank you! 😄
